let contacts = [
    {
        "color": "#5f9ea0",
        "name": "Adam Wheeler",
        "email": "Wheeler@gmail.com",
        "phone": "+49 171 3920001",
        "firstLetter": "A",
        "lastLetter":"W",
    },
    {
        "color": "#00ffff",
        "name": "Bernd Mueller",
        "email": "Mueller@gmail.com",
        "phone": "+49 171 3920004",
        "firstLetter": "B",
        "lastLetter":"M",
    },
    {
        "color": "#ff8c00",
        "name": "Christian Fischer",
        "email": "Lanz33@gmail.com",
        "phone": "+49 175 6065860",
        "firstLetter": "C",
        "lastLetter":"F",
    },
    {
        "color": "#8fbc8f",
        "name": "Francis Meissner",
        "email": "Meissner@gmail.com",
        "phone": "+49 171 3920023",
        "firstLetter": "F",
        "lastLetter":"M",
    },
    {
        "color": "#ff1493",
        "name": "Jamal Aziz",
        "email": "Aziz99@gmail.com",
        "phone": "+49 171 3920077",
        "firstLetter": "J",
        "lastLetter":"A",
    },
    {
        "color": "#00bfff",
        "name": "Janette Hollborn",
        "email": "Hollborn@gmail.com",
        "phone": "+49 171 3920034",
        "firstLetter": "J",
        "lastLetter":"H",
    },
    {
        "color": "#ff00ff",
        "name": "Leonore Miller",
        "email": "RealMiller@gmail.com",
        "phone": "+49 171 3920022",
        "firstLetter": "L",
        "lastLetter":"M",
    },
    {
        "color": "#daa520",
        "name": "Kim Vanderhorst",
        "email": "Vanderhorst@gmail.com",
        "phone": "+49 171 3920018",
        "firstLetter": "K",
        "lastLetter":"V",
    },
    {
        "color": "#adff2f",
        "name": "Jessica Brand",
        "email": "Brandalarm@gmail.com",
        "phone": "+49 171 3920044",
        "firstLetter": "J",
        "lastLetter":"B",
    },
    {
        "color": "#cd5c5c",
        "name": "Kim Seidel",
        "email": "Seidel1337@gmail.com",
        "phone": "+49 171 3920088",
        "firstLetter": "K",
        "lastLetter":"S",
    },
    {
        "color": "#f0e68c",
        "name": "Laura Wüst",
        "email": "wuest.in.action@gmail.com",
        "phone": "+49 171 3920034",
        "firstLetter": "L",
        "lastLetter":"W",
    },
    {
        "color": "#e6e6fa",
        "name": "Martin Gruber",
        "email": "gruber.martin@gmail.com",
        "phone": "+49 171 3920046",
        "firstLetter": "M",
        "lastLetter":"G",
    },
    {
        "color": "#f08080",
        "name": "Renate Schmitz",
        "email": "renate.schmitz@gmail.com",
        "phone": "+49 171 3920057",
        "firstLetter": "R",
        "lastLetter":"S",
    },
    {
        "color": "#d3d3d3",
        "name": "Sara Sweeny",
        "email": "sweeny.bussines@gmail.com",
        "phone": "+49 171 3920029",
        "firstLetter": "S",
        "lastLetter":"S",
    },
    {
        "color": "#20b2aa",
        "name": "Simone Lammer",
        "email": "Simone.Lammer@gmail.com",
        "phone": "+49 171 3920031",
        "firstLetter": "S",
        "lastLetter":"L",
    },
    {
        "color": "#00ff00",
        "name": "Verona Bricks",
        "email": "Bricks.consultant@gmail.com",
        "phone": "+49 171 3920055",
        "firstLetter": "V",
        "lastLetter":"B",
    },

]